### PR TITLE
introduce apt_src_enable, fixes #14

### LINKED ISSUE #14: option to enable source repository
e.g. the `deb-src` lines

we don't have them enabled by default and it would be nice to set that with this role!

### PR DESCRIPTION
**Pull request by davidak**
tested on Ubuntu 12.04 / 14.04 / 16.04

### CODE REVIEW

**Comment by tersmitten** [comment]
Look good! If you've wanted to test Debian you can just clone the repo and run:

```
vagrant up --provision
```

This will spin-up all supported Operating systems

**Comment by davidak** [comment]
I updated my vagrant but it don't work.

```
The provider 'VirtualBox' could not be found, but was requested to
back the machine 'ubuntu-1204'. Please use a provider that exists.
```

If you are able to just run it, please test debian. But i'm pretty sure it works also :)

**Comment by tersmitten** [comment]
> If you are able to just run it, please test debian. But i'm pretty sure it works also :)

Me too, but I'll check it just to be sure

**Comment by tersmitten** [comment]
I made some minor fixes in #18. I'll merge it when the tests are done

**Pull request merged**
