### PR TITLE
Add option to configure apt

### PR DESCRIPTION
**Pull request by Aisbergg**
This PR adds the possibility to configure APT with this role. When `ansible_manage_config` is set to `true`, the role will generate the `/etc/apt/apt.conf` using the configuration specified by `ansible_config`.

Example:

```yaml
apt_manage_config: true
apt_config:
  APT:
    Install-Recommends: false
    Install-Suggests: false
    Get:
      Fix-Broken: true
```

will result in (`/etc/apt/apt.conf`):
```plaintext
//
// This file is managed by Ansible. Do NOT edit this file manually!
//

APT {
  Install-Recommends "false";
  Install-Suggests "false";
  Get {
    Fix-Broken "true";
  };
};
```

### CODE REVIEW

**Comment by tersmitten** [comment]
Nice addition. Have you considered something like this? https://github.com/Oefenweb/ansible-dnsmasq#example-with-configuration-caching

The `dnsmasq_dnsmasq_conf` variable. This should give more flexibility.

**Comment by Aisbergg** [comment]
I do like the idea of using YAML to configure my applications.

- Single Interface: It fits right in with the rest of Ansible and I don't have to care to much about the underlying syntax of the applications, like the syntax of the APT config.
- Flexible: It gives me all the flexibilty I need, I think I can represent any option listed in [apt.conf(5)](https://manpages.debian.org/jessie/apt/apt.conf.5.en.html). It is less flexible in a sense, that I cannot define comments, which I prefer to keep in my Ansible configuration anyway
- Offer Defaults (doesn't apply here): Because YAML is parsed by Ansible, it can be changed before the configuration is rendered. This is nice in case you want to supply default values. Example: [Defaults](https://github.com/Aisbergg/ansible-role-dnscrypt-proxy/blob/4eeea0ff0d8e49f748558df8a81dee9588e55ae7/vars/main.yml#L14-L41) and [user configuration](https://github.com/Aisbergg/ansible-role-dnscrypt-proxy#example-playbook)


Some examples taken from [apt.conf(5)](https://manpages.debian.org/jessie/apt/apt.conf.5.en.html):
```
Acquire::Languages { "environment"; "de"; "en"; "none"; "fr"; };

DPkg::NoTriggers "true";
DPkg::ConfigurePending "true";
DPkg::TriggersPending "true";
PackageManager::Configure "smart";
```

Represented as YAML:
```yaml
Acquire:
  Languages:
    - "environment"
    - "de"
    - "en"
    - "none"
    - "fr"

DPkg:
  NoTriggers: true
  ConfigurePending: true
  TriggersPending: true

PackageManager:
  Configure: smart
```

**Comment by tersmitten** [comment]
I understand your argument, but I find the PR overly complex and tend to prefer the other way. Is this still useful to you?

**Comment by Aisbergg** [comment]
I don't mind, if you supply an option to configure APT in the same fashion as your dnsmasq role that would be fine by me

**Comment by tersmitten** [comment]
Fixed in https://github.com/Oefenweb/ansible-apt/releases/tag/v2.4.0

**Pull request closed without merging**
